---
#- name: Clone dotfiles
#  git: repo=https://github.com/sharma-mohit/dotfiles.git dest=/Users/mohit/dotfiles recursive=yes

- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: dotfiles/bin/install
  shell: bin/install
  args:
    chdir: /Users/mohit/dotfiles/
  ignore_errors: yes

- name: dotfiles/bin/setup_osx
  shell: bin/setup_osx
  args:
    chdir: /Users/mohit/dotfiles/
  ignore_errors: yes

- name: iterm settings
  shell: contrib/install-settings.sh
  args:
    chdir: /Users/mohit/dotfiles/macosx-iterm2-settings/
  ignore_errors: yes



- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: '{{dockitems_to_remove}}'

- name: Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: '{{dockitems_to_persist}}'

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: '{{dockitems_to_persist}}'

